"""Mapping of Python import module names to PyPI distribution package names."""
from typing import Dict, Optional

IMPORT_TO_PACKAGE_MAP: Dict[str, str] = {
    "cv2": "opencv-python",
    "PIL": "Pillow",
    "sklearn": "scikit-learn",
    "yaml": "PyYAML",
    "bs4": "beautifulsoup4",
    "dotenv": "python-dotenv",
    "jwt": "PyJWT",
    "fitz": "PyMuPDF",
    "serial": "pyserial",
    "psycopg2": "psycopg2-binary",
    "docx": "python-docx",
    "pptx": "python-pptx",
    "magic": "python-magic",
    "OpenGL": "PyOpenGL",
    "git": "GitPython",
    "telegram": "python-telegram-bot",
    "discord": "discord.py",
    "dateutil": "python-dateutil",
    "Bio": "biopython",
    "skimage": "scikit-image",
    "Crypto": "pycryptodome",
    "websocket": "websocket-client",
    "multipart": "python-multipart",
    "jose": "python-jose",
    "josejwt": "python-jose",
    "fastapi": "fastapi",
    "uvicorn": "uvicorn",
    "pydantic": "pydantic",
    "flask": "Flask",
    "django": "Django",
    "requests": "requests",
    "aiohttp": "aiohttp",
    "httpx": "httpx",
    "numpy": "numpy",
    "pandas": "pandas",
    "scipy": "scipy",
    "matplotlib": "matplotlib",
    "seaborn": "seaborn",
    "torch": "torch",
    "torchvision": "torchvision",
    "torchaudio": "torchaudio",
    "tensorflow": "tensorflow",
    "keras": "keras",
    "transformers": "transformers",
    "huggingface_hub": "huggingface_hub",
    "sqlalchemy": "SQLAlchemy",
    "alembic": "alembic",
    "tortoise": "tortoise-orm",
    "peewee": "peewee",
    "pymongo": "pymongo",
    "redis": "redis",
    "celery": "celery",
    "rich": "rich",
    "typer": "typer",
    "click": "click",
    "tqdm": "tqdm",
    "pytest": "pytest",
    "pydantic_settings": "pydantic-settings",
    "starlette": "starlette",
    "jinja2": "Jinja2",
    "markupsafe": "MarkupSafe",
    "werkzeug": "Werkzeug",
    "streamlit": "streamlit",
    "gradio": "gradio",
    "dash": "dash",
    "plotly": "plotly",
    "bokeh": "bokeh",
}


def get_package_for_import(import_name: str) -> str:
    """Returns the PyPI distribution package name for an import name."""
    clean_name = import_name.strip()
    return IMPORT_TO_PACKAGE_MAP.get(clean_name, clean_name)
